---
title: Destroy Today 2016
url: http://2016.destroytoday.com
timezone: UTC
collections:
  blog:
    title: Blog
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
permalink: pretty
