---
title: Destroy Today 2016
url: http://2016.destroytoday.com
timezone: UTC
collections:
  blog:
    title: Blog
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    type: blog
  values:
    timestamp?: true
permalink: pretty
sass:
  sass_dir: css/_includes
  style: compressed
