---
title: Destroy Today
url: http://destroytoday.com
timezone: America/New_York
author: Jonnie Hallman
collections:
  writings:
    title: Writings
    output: true
  interviews:
    title: Interviews
    output: true
  talks:
    title: Talks
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
    timestamp?: true
permalink: pretty
sass:
  sass_dir: css/_includes
  style: compressed
