---
title: Destroy Today
timezone: America/New_York
collections:
  blog:
    title: Blog
    output: true
  interviews:
    title: Interviews
    output: true
    archive?: true
  posts:
    title: Posts
    output: true
  talks:
    title: Talks
    output: true
  uploads:
    title: Uploads
    output: true
  writings:
    title: Writings
    output: true
    archive?: true
defaults:
- scope:
    path: ''
  values:
    layout: default
    timestamp?: true
description: The personal website of designer/dev, Jonnie Hallman.
author: Jonnie Hallman
permalink: pretty
sass:
  sass_dir: css/_includes
  style: compressed
