---
title: Destroy Today 2016
url: http://2016.destroytoday.com
timezone: America/New_York
collections:
  blog:
    title: Blog
    output: true
  talks:
    title: Talks
    output: true
  interviews:
    title: Interviews
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: blog
  values:
    timestamp?: true
- scope:
    path: ''
    type: talks
  values:
    timestamp?: true
- scope:
    path: ''
    type: interviews
  values:
    timestamp?: true
permalink: pretty
sass:
  sass_dir: css/_includes
  style: compressed
